name: Release and Publish

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'      

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci
      
      - name: Generate Changesets
        run: node scripts/generate-changeset.js

      - name: Debug Changesets
        run: |
          echo "Current directory:"
          pwd
          echo "List root directory:"
          ls -la
          echo "List packages directory:"
          ls -la packages
          echo "Content of root package.json:"
          cat package.json
          echo "Content of .changeset/config.json:"
          cat .changeset/config.json
          echo "List .changeset directory:"
          ls -la .changeset

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: update versions, changelog, and package-lock.json" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin HEAD:main || (git status && git diff && exit 1)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          publish: npx changeset version --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}